twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/src/Resources/': ~
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
#
