root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_profile_show
        permanent: true

api_user_get:
    path: /api/user
    defaults:
        _controller: App\Controller\UserApiController::getUser
